### ISSUE TITLE
Current release has an Odin Inspector attribute

### ISSUE THREAD

**Issue by bloeys** [IntoTheDev/MultiTag-System-for-Unity#3]
Hello!

First of all thanks a lot for this, it looks a really good made tool and I will hopefully use it in a major project of mind :D
I got the unity package on the release from 2 days ago but upon importing I saw this in `Tag.cs`:

```cs
[Button]
private void Clear()
{
    _entities.Clear();
}
```

The button attribute is part of Odin inspector and it seems you forgot to comment it out with a compiler directive. I wanted to do a PR but I was confused not to find the function in the repo, maybe the repo is outdated?

Anyway just wanted to point this out, and thanks again :)

P.S. The `Test Results` section of the readme doesnt seem to have actual test results, just a screenshot of the inspector.

**Comment by IntoTheDev** [comment]
Hello!

Thanks for opening issue! I updated Package where i removed that method and also updated Performance Test in Readme

**Comment by bloeys** [comment]
Thank you!
And good luck with projects :D
