### ISSUE TITLE
Standalone build warning

### ISSUE THREAD

**Issue by lemoissonneur** [IntoTheDev/MultiTag-System-for-Unity#4]
Hello !
This var is only used in editor code and generate a warning when building. Shouldn't it be declared inside a `#if  UNITY_EDITOR ... #endif` as well ?
```c#
public sealed class Taggable : MonoBehaviour
{
        ...
        private static Tag[] _all = null;
        ...
}
```
![Capture](https://user-images.githubusercontent.com/17100561/113118374-b2641400-920f-11eb-9df8-462c7764e2d4.PNG)
```c#
public sealed class Taggable : MonoBehaviour
{
...
#if UNITY_EDITOR
        private static Tag[] _all = null;
#endif
...
}
```

Thank you for this package !

**Comment by IntoTheDev** [comment]
Hello! If you declare this variable inside `#UNITY_EDITOR` directive then you will get serialization error/warning in build. Currently it works just fine except warning in editor, no need to put this inside directive.

**Comment by lemoissonneur** [comment]
As far as i know, unity doesn't serialize static properties, and it didn't trigger any serialization error for me (2019.4.8f1).

**Comment by IntoTheDev** [comment]
Ah, yes. You're totally right, thanks! :) I added this field to UNITY_EDITOR directive in last commit.
