### ISSUE TITLE
[Feature Request] Equivalent of Unity FindWithTag/FindGameObjectsWithTag

### ISSUE THREAD

**Issue by hcorion** [IntoTheDev/MultiTag-System-for-Unity#6]
I see you store a reference to the GameObject hash, this feature would be trivial if you store a reference to the object as well? It seems to me that this would be blazingly fast compared to Unity's FindWithTag, which is part of the reason why I'm interested in seeing that happen. Are there any concerns with storing the GameObject references themselves in the Tag?

**Comment by IntoTheDev** [comment]
Hello! Believe me or not but yesterday I just though about the same thing because I needed to iterate through some tagged objects in my game :) I will implement this feature today/tomorrow.

**Comment by IntoTheDev** [comment]
Done and tested! :)
